// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankLib.Model;

[Table("BankExampleWithEF_Address")]
public partial class Address
{
    public Address(int addressId, int cityId, string streetName, int houseNumber, City city)
    {
        AddressId = addressId;
        CityId = cityId;
        StreetName = streetName;
        HouseNumber = houseNumber;
        City = city;
    }

    public Address():this(0,0,"DefaultVej",1,new City())
    {
        
    }

    [Key]
    [Column("Address_Id")]
    public int AddressId { get; set; }

    [Column("City_Id")]
    public int CityId { get; set; }

    [Required]
    [StringLength(30)]
    public string StreetName { get; set; }

    public int HouseNumber { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Customer> BankExampleWithEfCustomers { get; set; } = new List<Customer>();

    [InverseProperty("Address")]
    public virtual ICollection<Employee> BankExampleWithEfEmployees { get; set; } = new List<Employee>();

    [ForeignKey("CityId")]
    [InverseProperty("BankExampleWithEfAddresses")]
    public virtual City City { get; set; }
}