// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BankLib.Model;

[Table("BankExampleWithEF_Customer")]
public partial class Customer
{
    public Customer(int customerId, int addressId, int mainAccountId, string firstName, string lastName, string mail, string phoneNumber, string password, string gender, bool isDeleted, Address address, MainAccount mainAccount)
    {
        CustomerId = customerId;
        AddressId = addressId;
        MainAccountId = mainAccountId;
        FirstName = firstName;
        LastName = lastName;
        Mail = mail;
        PhoneNumber = phoneNumber;
        Password = password;
        Gender = gender;
        IsDeleted = isDeleted;
        Address = address;
        MainAccount = mainAccount;
    }

    public Customer():this(0,0,0,"Default","Default","Default@mail.dk","00000000","Default","Mand",false,new Address(),new MainAccount())
    {
        
    }

    [Key]
    [Column("Customer_Id")]
    public int CustomerId { get; set; }

    [Column("Address_Id")]
    public int AddressId { get; set; }

    [Column("MainAccount_Id")]
    public int MainAccountId { get; set; }

    [Required]
    [StringLength(30)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(30)]
    public string LastName { get; set; }

    [Required]
    public string Mail { get; set; }

    [Required]
    [StringLength(8)]
    public string PhoneNumber { get; set; }

    [Required]
    public string Password { get; set; }

    [Required]
    [StringLength(30)]
    public string Gender { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("BankExampleWithEfCustomers")]
    public virtual Address Address { get; set; }

    [InverseProperty("AffectedCustomer")]
    public virtual ICollection<EmployeeLog> BankExampleWithEfEmployeeLogs { get; set; } = new List<EmployeeLog>();

    [InverseProperty("Customer")]
    public virtual ICollection<Transaction> BankExampleWithEfTransactions { get; set; } = new List<Transaction>();

    [ForeignKey("MainAccountId")]
    [InverseProperty("BankExampleWithEfCustomers")]
    public virtual MainAccount MainAccount { get; set; }

    public override string ToString()
    {
        return $"{{Class=Customer: {nameof(CustomerId)}={CustomerId.ToString()}, {nameof(AddressId)}={AddressId.ToString()}, {nameof(MainAccountId)}={MainAccountId.ToString()}, {nameof(FirstName)}={FirstName}, {nameof(LastName)}={LastName}, {nameof(Mail)}={Mail}, {nameof(PhoneNumber)}={PhoneNumber}, {nameof(Password)}={Password}, {nameof(Gender)}={Gender}, {nameof(IsDeleted)}={IsDeleted.ToString()}, {nameof(Address)}={Address}, {nameof(MainAccount)}={MainAccount}}}";
    }
}