// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankLib.Model;

[Table("BankExampleWithEF_Customer")]
public partial class Customer
{
    [Key]
    [Column("Customer_Id")]
    public int CustomerId { get; set; }

    [Column("Address_Id")]
    public int AddressId { get; set; }

    [Column("MainAccount_Id")]
    public int MainAccountId { get; set; }

    [Required]
    [StringLength(30)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(30)]
    public string LastName { get; set; }

    [Required]
    public string Mail { get; set; }

    [Required]
    [StringLength(8)]
    public string PhoneNumber { get; set; }

    [Required]
    public string Password { get; set; }

    [Required]
    [StringLength(30)]
    public string Gender { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("BankExampleWithEfCustomers")]
    public virtual Address Address { get; set; }

    [InverseProperty("AffectedCustomer")]
    public virtual ICollection<EmployeeLog> BankExampleWithEfEmployeeLogs { get; set; } = new List<EmployeeLog>();

    [InverseProperty("Customer")]
    public virtual ICollection<Transaction> BankExampleWithEfTransactions { get; set; } = new List<Transaction>();

    [ForeignKey("MainAccountId")]
    [InverseProperty("BankExampleWithEfCustomers")]
    public virtual MainAccount MainAccount { get; set; }
}