// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankLib.Model;

[Table("BankExampleWithEF_Employee")]
public partial class Employee
{
    public Employee(int employeeId, int addressId, int positionId, int departmentId, int mainAccountId, string firstName, string lastName, string mail, string phoneNumber, string password, string gender, bool isDeleted, string imagePath, Address address, Department department, MainAccount mainAccount, Position position)
    {
        EmployeeId = employeeId;
        AddressId = addressId;
        PositionId = positionId;
        DepartmentId = departmentId;
        MainAccountId = mainAccountId;
        FirstName = firstName;
        LastName = lastName;
        Mail = mail;
        PhoneNumber = phoneNumber;
        Password = password;
        Gender = gender;
        IsDeleted = isDeleted;
        ImagePath = imagePath;
        Address = address;
        Department = department;
        MainAccount = mainAccount;
        Position = position;
    }

    public Employee():this(0,0,0,0,0,"Default","Default","Default@mail.dk","00000000","Default","Mand",false,"Default",new Address(),new Department(),new MainAccount(),new Position())
    {
        
    }

    [Key]
    [Column("Employee_Id")]
    public int EmployeeId { get; set; }

    [Column("Address_Id")]
    public int AddressId { get; set; }

    [Column("Position_Id")]
    public int PositionId { get; set; }

    [Column("Department_Id")]
    public int DepartmentId { get; set; }

    [Column("MainAccount_Id")]
    public int MainAccountId { get; set; }

    [Required]
    [StringLength(30)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(30)]
    public string LastName { get; set; }

    [Required]
    public string Mail { get; set; }

    [Required]
    [StringLength(8)]
    public string PhoneNumber { get; set; }

    [Required]
    public string Password { get; set; }

    [Required]
    [StringLength(30)]
    public string Gender { get; set; }

    public bool IsDeleted { get; set; }

    [Required]
    public string ImagePath { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("BankExampleWithEfEmployees")]
    public virtual Address Address { get; set; }

    [InverseProperty("AffectedEmployee")]
    public virtual ICollection<EmployeeLog> BankExampleWithEfEmployeeLogAffectedEmployees { get; set; } = new List<EmployeeLog>();

    [InverseProperty("ResponsibleEmployee")]
    public virtual ICollection<EmployeeLog> BankExampleWithEfEmployeeLogResponsibleEmployees { get; set; } = new List<EmployeeLog>();

    [InverseProperty("Employee")]
    public virtual ICollection<Transaction> BankExampleWithEfTransactions { get; set; } = new List<Transaction>();

    [ForeignKey("DepartmentId")]
    [InverseProperty("BankExampleWithEfEmployees")]
    public virtual Department Department { get; set; }

    [ForeignKey("MainAccountId")]
    [InverseProperty("BankExampleWithEfEmployees")]
    public virtual MainAccount MainAccount { get; set; }

    [ForeignKey("PositionId")]
    [InverseProperty("BankExampleWithEfEmployees")]
    public virtual Position Position { get; set; }

    public override string ToString()
    {
        return $"{{Class=Employee: {nameof(EmployeeId)}={EmployeeId.ToString()}, {nameof(AddressId)}={AddressId.ToString()}, {nameof(PositionId)}={PositionId.ToString()}, {nameof(DepartmentId)}={DepartmentId.ToString()}, {nameof(MainAccountId)}={MainAccountId.ToString()}, {nameof(FirstName)}={FirstName}, {nameof(LastName)}={LastName}, {nameof(Mail)}={Mail}, {nameof(PhoneNumber)}={PhoneNumber}, {nameof(Password)}={Password}, {nameof(Gender)}={Gender}, {nameof(IsDeleted)}={IsDeleted.ToString()}, {nameof(ImagePath)}={ImagePath}, {nameof(Address)}={Address}, {nameof(Department)}={Department}, {nameof(MainAccount)}={MainAccount}, {nameof(Position)}={Position}}}";
    }
}