// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankLib.Model;

[Table("BankExampleWithEF_MainAccount")]
public partial class MainAccount
{
    public MainAccount(int mainAccountId)
    {
        MainAccountId = mainAccountId;
    }

    public MainAccount():this(0)
    {
        
    }

    [Key]
    [Column("MainAccount_Id")]
    public int MainAccountId { get; set; }

    [InverseProperty("MainAccount")]
    public virtual ICollection<Account> BankExampleWithEfAccounts { get; set; } = new List<Account>();

    [InverseProperty("MainAccount")]
    public virtual ICollection<Customer> BankExampleWithEfCustomers { get; set; } = new List<Customer>();

    [InverseProperty("MainAccount")]
    public virtual ICollection<Employee> BankExampleWithEfEmployees { get; set; } = new List<Employee>();
}