// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankLib.Model;

[Table("BankExampleWithEF_Transaction")]
public partial class Transaction
{
    [Key]
    [Column("Transaction_Id")]
    public int TransactionId { get; set; }

    [Column("Employee_Id")]
    public int? EmployeeId { get; set; }

    [Column("Customer_Id")]
    public int? CustomerId { get; set; }

    public int Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    [Required]
    [StringLength(30)]
    public string Description { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("BankExampleWithEfTransactions")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("BankExampleWithEfTransactions")]
    public virtual Employee Employee { get; set; }
}