// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankLib.Model;

[Table("BankExampleWithEF_Transaction")]
public partial class Transaction
{
    public Transaction(int transactionId, int? employeeId, int? customerId, int accountId, int amount, DateTime date, string type, string description, int current_Balance)
    {
        TransactionId = transactionId;
        EmployeeId = employeeId;
        CustomerId = customerId;
        AccountId = accountId;
        Amount = amount;
        Date = date;
        Type = type;
        Description = description;
        Current_Balance = current_Balance;
    }

    public Transaction():this(0,null,null,0,0,DateTime.UtcNow,"Default","Default",0)
    {
        
    }

    [Key]
    [Column("Transaction_Id")]
    public int TransactionId { get; set; }

    [Column("Employee_Id")]
    public int? EmployeeId { get; set; }

    [Column("Customer_Id")]
    public int? CustomerId { get; set; }

    [Column("Account_Id")]
    public int AccountId { get; set; }

    public int Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    [Required]
    [StringLength(30)]
    public string Description { get; set; }

    [Column("Current_Balance")]
    public int Current_Balance { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("BankExampleWithEfTransactions")]
    public virtual Account Account { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("BankExampleWithEfTransactions")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("BankExampleWithEfTransactions")]
    public virtual Employee Employee { get; set; }
}