// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankLib.Model;

[Table("BankExampleWithEF_ZipCodeTable")]
public partial class ZipCodeTable
{
    public ZipCodeTable(int zipCodeId, int zipCode)
    {
        ZipCodeId = zipCodeId;
        ZipCode = zipCode;
    }

    public ZipCodeTable():this(0,0000)
    {
        
    }

    [Key]
    [Column("ZipCode_Id")]
    public int ZipCodeId { get; set; }

    public int ZipCode { get; set; }

    [InverseProperty("ZipCode")]
    public virtual ICollection<City> BankExampleWithEfCities { get; set; } = new List<City>();
}